apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: wisecow
        image: ghcr.io/meeramohan323/wisecow:latest
        ports:
        - containerPort: 3000
