
name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: pure-spirit-123456-m1

    - name: Get GKE credentials
      env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

      run: |
        echo $GCP_SA_KEY | base64 --decode > $HOME/gcloud-key.json
        gcloud auth activate-service-account --key-file=$HOME/gcloud-key.json
        gcloud container clusters get-credentials autopilot-cluster-1 --zone europe-west2 --project pure-spirit-123456-m1

    - name: Deploy to GKE
      run: |
        kubectl apply -f k8s/deployment.yaml --validate=false
        kubectl apply -f k8s/service.yaml --validate=false
