name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          service_account_key: |
            ${{ secrets.GCP_SA_KEY }}

      - name: Authenticate with Google Cloud
        run: |
          gcloud auth activate-service-account --key-file=key.json
          gcloud container clusters get-credentials autopilot-cluster-1 --zone europe-west2 --pure-spirit-123456-m1

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
