name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: pure-spirit-123456-m1
        service_account_key: ${{ secrets.GKE_SA_KEY }}

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/ pure-spirit-123456-m1/wisecow:latest .
        docker push gcr.io /pure-spirit-123456-m1/wisecow:latest

    - name: Set up Kubernetes context
      run: |
        gcloud container clusters get-credentials wisecow-cluster --zone us-central1-a
        kubectl config view

    - name: Deploy to GKE
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
