name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '306.0.0'  # Example version number, replace with the desired version

      - name: Configure Docker CLI
        run: |
          echo $GCP_SA_KEY_FILE | base64 -d > /tmp/key.json
          gcloud auth activate-service-account --key-file=/tmp/key.json

      # Add more steps for deployment...
